<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/db.php'; require_once __DIR__ . '/../includes/auth.php'; requireLogin();
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); exit('Method not allowed.'); }
verifyCsrf($_POST['csrf_token'] ?? null); $invoiceId = filter_input(INPUT_POST, 'invoice_id', FILTER_VALIDATE_INT); $reference = trim((string) ($_POST['reference_number'] ?? '')); $file = $_FILES['receipt'] ?? null; $user = currentUser();
if (!$invoiceId || $reference === '' || !$file || $file['error'] !== UPLOAD_ERR_OK) redirectWith('../tenant/pay_bill.php','error','Valid payment details are required.');
$stmt = $pdo->prepare("SELECT * FROM invoices WHERE id = :id AND tenant_id = :tenant_id AND status IN ('unpaid','overdue') LIMIT 1"); $stmt->execute([':id'=>$invoiceId, ':tenant_id'=>$user['id']]); $invoice = $stmt->fetch(); if (!$invoice) redirectWith('../tenant/pay_bill.php','error','Invoice is unavailable.');
$allowed = ['image/jpeg'=>'jpg','image/png'=>'png']; $mime = (new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']); if (!isset($allowed[$mime]) || $file['size'] > 5 * 1024 * 1024) redirectWith('../tenant/pay_bill.php','error','Receipt must be a PNG or JPEG up to 5 MB.');
$directory = __DIR__ . '/../uploads/receipts'; if (!is_dir($directory) && !mkdir($directory, 0750, true)) redirectWith('../tenant/pay_bill.php','error','Upload directory is unavailable.'); $filename = bin2hex(random_bytes(16)) . '.' . $allowed[$mime]; if (!move_uploaded_file($file['tmp_name'], $directory . '/' . $filename)) redirectWith('../tenant/pay_bill.php','error','Receipt upload failed.');
$pdo->beginTransaction(); try { $stmt = $pdo->prepare("INSERT INTO payments (invoice_id, tenant_id, payment_method, amount, reference_number, proof_image_url, status) VALUES (:invoice_id,:tenant_id,'gcash_manual',:amount,:reference,:proof,'pending')"); $stmt->execute([':invoice_id'=>$invoiceId, ':tenant_id'=>$user['id'], ':amount'=>$invoice['total_amount'], ':reference'=>$reference, ':proof'=>'uploads/receipts/' . $filename]); $stmt = $pdo->prepare("UPDATE invoices SET status = 'pending' WHERE id = :id"); $stmt->execute([':id'=>$invoiceId]); $pdo->commit(); } catch (Throwable $exception) { $pdo->rollBack(); @unlink($directory . '/' . $filename); redirectWith('../tenant/pay_bill.php','error','Payment could not be saved.'); } redirectWith('../tenant/dashboard.php','success','Manual payment submitted for review.');